### ISSUE TITLE
Some manga like Toradora! isn't downloading.

### ISSUE THREAD

**Issue by OnuOskar** [notprash/manga-cli#1]
I have tested this with multiple different manga, some like One Punch Man and One Piece work perfectly, while others like Toradora! don't. They don't appear in ~/.cache/manga-cli. When I try to read Toradora! it gives me an error saying: error: cannot open /home/user/.cache/manga-cli/Toradora!-1.pdf: No such file or directory
error: could not open document
It opens zathura with a black screen and [No name] in the bottom left corner, and a title saying: org.pwmt.zathura. I am using arch linux with xfce, and terminology as the terminal.

Edit: I am suspecting this is because the manga Toradora!, has an exclamation mark in the name, but I am not sure yet

**Comment by OnuOskar** [comment]
Ok, I am pretty sure that this is because of special characters like ! and , in the name. Hope this gets fixed soon

**Comment by notprash** [comment]
this is the problem with the link of the manga which is quite different from the other one. 

One piece chapter one link:
https://readmanganato.com/manga-aa951409/chapter-1

Toradora! chapter one link:
https://mangakakalot.com/chapter/toradora/chapter_1


Thanks for the issue, I will fix it

**Comment by notprash** [comment]
```bash
git pull
./manga-cli
```

issue fixed.
