### ISSUE TITLE
could not open document

### ISSUE THREAD

**Issue by rhyn0rang3r** [notprash/manga-cli#10]
every manga i try to open i always get a failure of

```next chapter (n)```
```quit (q)```
```previous chapter (p)```
```Enter Option: error: could not open document```

i've tried opening other things with zathura and i don't have any issues with them, so is it something on my end or am i mising something.

**Comment by patgamer351** [comment]
I only this error when zathura-cb wasn't installed. Make sure you have zathura-cb installed? And make sure that manga-cli is up to the latest version
