### ISSUE TITLE
better usement of pup

### ISSUE THREAD

**Issue by patgamer351** [notprash/manga-cli#11]
When using pup please use "-p" because I've noticed, so far, that pup changes apostrophes to the HTML code for an apostrophe. Thanks!

**Comment by notprash** [comment]
I didn't get you. Could you elaborate?

**Comment by patgamer351** [comment]
when you use "pup" apostrophes are still encoded but when you use "pup -p " the apostrophes are decoded. sorry for not being clear earlier.

**Comment by notprash** [comment]
I don't think there is much use of it, I am closing this issue.
