### ISSUE TITLE
[Feature Request]: pdf instead of cbz 

### ISSUE THREAD

**Issue by ThamognyaKodi** [notprash/manga-cli#13]
I would like to use this on a mac but `zathura` and `zathura-cb` don't work. Now this works perfectly on my Linux machine but I would like to try to use this on a mac.  I am requesting a change of complication from cbz to pdf if possible or any recommendations for cbz viewers that can be accessed via the terminal like `zathura`.

**Comment by fossimprove** [comment]
Mentioning this #2 

You can edit script for it.
Refer this commit for it https://github.com/notprash/manga-cli/commit/ad7880457be9a9c020ca4ad680e4fab6b340a4b1

@notprash  Maybe you could add both option to download to pdf or cbz with query (-p & -z) ?
As some will prefer pdf as they are used everywhere

**Comment by ThamognyaKodi** [comment]
I really like the idea of querying for pdf or cbz @fossimprove. Also thank you for the links, it helps me a lot.

**Comment by notprash** [comment]
Thanks for your feature request. I will add option for change the file type.

**Comment by notprash** [comment]
> Mentioning this #2
> 
> You can edit script for it. Refer this commit for it [ad78804](https://github.com/notprash/manga-cli/commit/ad7880457be9a9c020ca4ad680e4fab6b340a4b1)
> 
> @notprash Maybe you could add both option to download to pdf or cbz with query (-p & -z) ? As some will prefer pdf as they are used everywhere

what about a variable in the script 
```bash
file_format="cbz" # or pdf
```

**Comment by ThamognyaKodi** [comment]
Well I have got my answer and understood what to do. Thank you for the support everyone.
