### ISSUE TITLE
An option to extract it in CBZ too

### ISSUE THREAD

**Issue by fossimprove** [notprash/manga-cli#2]
PDF format sure is great to read all content, but recently I have noticed that in some chapter all images would be spaced a lot.

But then I zip them into CBZ, that space was not there. Although spaces still exist for webtoons (long strip)
Manga are better available in CBZ format, so why not.

I simply uncommented convert command and added another command like
`zip $image_dir$name-$chapterNumber.cbz $(ls -v $image_dir*.jpg)`

Also, Can the steps/script be task spooled (tsp) ? Like process in background?
I have added 
`tsp zathura "$image_dir$name-$chapterNumber.cbz"`

So zathura is not integrated into terminal

I thought this was scraping mangareader(dot)to
It looks to be easily scraped too.
Finally, nice script !
Made me easy to glimpse and pilot study some manga

**Comment by notprash** [comment]
Nice Idea! I will work on it.

**Comment by notprash** [comment]
You have changed something and already have created. Please create pull request.

**Comment by fossimprove** [comment]
I dont know to use github nor i know shell scripting.

As per my knowledge i had just replaced commands to get that idea.

Please do it yourself.
Thank you!

**Comment by notprash** [comment]
@fossimprove 

We have moved to cbz files and fixed the images not in the order.

Thanks for your contribution
