### ISSUE TITLE
Pages downloading, but disapearing

### ISSUE THREAD

**Issue by OnuOskar** [notprash/manga-cli#3]
So the pages are disapearing from ~/.cache/manga-cli before it can open the document. I also get an error saying: error: could not open document. Zathura just shows a black screen

**Comment by notprash** [comment]
have you tried updating?

```bash
git pull
sudo make
```

**Comment by OnuOskar** [comment]
Yes I have, when I do git pull it says: Already up to date

**Comment by notprash** [comment]
> Yes I have, when I do git pull it says: Already up to date

did you run 
```
sudo make
```

**Comment by OnuOskar** [comment]
yes I did

**Comment by notprash** [comment]
could like explain in more detail like how it is happening. Is it happening with all the mangas?

**Comment by OnuOskar** [comment]
Wait, I tried updating all the packages I use to zip files, and now it works.
