### ISSUE TITLE
html character decoding error and a could not open document error

### ISSUE THREAD

**Issue by patgamer351** [notprash/manga-cli#4]
when i run your program and enter "ijiran" i get 

[1]Ijiranaide, Nagatoro-San
[2]Please Don&#39;t Bully Me, Nagatoro Comic Anthology

there is a "&#39;" instead of an apostrophe. 

secondly when i tried to select  "Ijiranaide, Nagatoro-San" i would get "error: could not open document". but, when i opened Jujutsu Kaisen it would work. I really admire your efforts in creating a manga-cli and I would really love to see it improve!!

**Comment by notprash** [comment]
so to select a manga, you have to write the number

**Comment by notprash** [comment]
This has something to do with the links of the chapters just like #1

**Comment by notprash** [comment]
fixed with the lastest commit 
```bash
git pull
sudo make
```
