### ISSUE TITLE
Anyway to get list or number of chapters available for the manga + Batch download

### ISSUE THREAD

**Issue by fossimprove** [notprash/manga-cli#5]
Number of available chapters will help us to choose and download from where we had left.

Even something like batch download?

**Comment by notprash** [comment]
I am thinking on working on adding total number of chapters. I will look in it.

**Comment by notprash** [comment]
do you mean something like this
```
Select Chapter [1-200]: 
```

**Comment by fossimprove** [comment]
NOTE : I came across another issue, For some manga the chapters are numbered in decimals (51.1, 51.2)
E.g. https://readmanganato.com/manga-zd976712
For this, unless we choose exact number, it won't download.

So I would request to also get list or grid fashion of available chapters.

Any means to batch downloaded, like between interval of numbers, or somewhat?

**Comment by notprash** [comment]
> NOTE : I came across another issue, For some manga the chapters are numbered in decimals (51.1, 51.2) E.g. https://readmanganato.com/manga-zd976712 For this, unless we choose exact number, it won't download.
> 
> So I would request to also get list or grid fashion of available chapters.
> 
> Any means to batch downloaded, like between interval of numbers, or somewhat?


What about when you get the enter chapter number prompt:
If you enter `Enter Chapter Number: list` it would list the chapters in the manga?

**Comment by notprash** [comment]
also please check the latest commit and the readme

**Comment by notprash** [comment]
Please checkout #8 . I am closing this issue.
