### ISSUE TITLE
Error: Unknown file type: 'inode/x-empty'

### ISSUE THREAD

**Issue by MeliodasZoom** [notprash/manga-cli#6]
I get the error message `error: Unknown file type: 'inode/x-empty'`

It works in the search feature, selection features but gets an error after that. I have all the dependencies and am not sure where the problem is.

**Comment by notprash** [comment]
have you installed `zathura-cb` package?

**Comment by patgamer351** [comment]
which manga did you try to download?

**Comment by MeliodasZoom** [comment]
I have installed package `zathura-cb`. I tried to download boruto manga, chapter 50.

 I use a Gentoo machine if you are wondering.

**Comment by notprash** [comment]
do you have some kind of screenshot of the error. So that we can understand better?

**Comment by MeliodasZoom** [comment]
![before_enter](https://user-images.githubusercontent.com/85227613/149510090-6886c05f-4f8c-4640-88f3-6121084d40da.png)


![after_enter](https://user-images.githubusercontent.com/85227613/149510100-eead5e9e-ead3-4331-8dfa-9be99fe79eed.png)

**Comment by fossimprove** [comment]
It works fine on my end.
I use arch and everything's up to date

**Comment by MeliodasZoom** [comment]
Well like I said I use Gentoo. I am currently using the 0.1.8 version of zathura-cb which might be the problem but that is only a speculation.

**Comment by notprash** [comment]
> Well like I said I use Gentoo. I am currently using the 0.1.8 version of zathura-cb which might be the problem but that is only a speculation.

Zathura-cb latest release is `0.1.9`.

**Comment by MeliodasZoom** [comment]
Well I will try to see if there I can upgrade by writing an ebuild later as there are no maintainers for the particular package. But for now I think you can close this issue.

**Comment by notprash** [comment]
can you list the files in `~/.cache/manga-cli` and also did you get `Getting Data....` text

**Comment by MeliodasZoom** [comment]
The files in the `~/.cache/manga-cli` is currently shows images of the chapters and yes I do see the getting data text. I am able to open the files using feh or sxiv but not zathura.

**Comment by MeliodasZoom** [comment]
Now I was able to open the file after a restart.  Not sure what happened but thank you for your time.
