### ISSUE TITLE
Line 58 error

### ISSUE THREAD

**Issue by rhyn0rang3r** [notprash/manga-cli#7]
```line 58: [: =: unary operator expected```

any ideas on how to fix this

**Comment by fossimprove** [comment]
Same here.
After the latest listing changes
#5

**Comment by notprash** [comment]
I think this is caused by the latest update. I will look into it

**Comment by notprash** [comment]
The listing command is kind of buggy right now.

**Comment by notprash** [comment]
update manga-cli and it should work
