### ISSUE TITLE
Listing rework

### ISSUE THREAD

**Issue by notprash** [notprash/manga-cli#8]
As the old listing command lend to numerous errors which stopped the main function of the script. I am thinking reworking like this:
```bash
manga-cli -l <manga-name>
```
this command will list the commands. I am open to any suggestions

**Comment by patgamer351** [comment]
I really like this feature but please move the query back to the "Search Manga:" and be able to select to download a manga from that list with the "Enter chapter number:" feature.

**Comment by fossimprove** [comment]
The listing works fantastically!
Maybe listing them in grid and adding colors would be a great option.

Thank you very much, it's developing greatly.
I'm sure if some YouTuber catches an eye on this script, it will reach much audience!
